import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Container, H1, H2, CTAButton } from "@/components/ui";
import { TREATMENTS } from "@/lib/treatments";
import { GoalIcon } from "@/components/care/GoalIcons";
import WholePersonBanner from "@/components/care/WholePersonBanner";

export const metadata: Metadata = { title: "Chiropractic Treatments & Care | Go Chiro Mobile", description: "Learn about chiropractic adjustments, soft tissue therapies, postural retraining, exercise, and electrotherapy provided at your location.", alternates: { canonical: "/treatments" } };
export default function Page() {
  return <article className="py-12 sm:py-16"><Container><H1>Treatments &amp; Care</H1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-ink">Many common muscle and joint conditions can be effectively managed with chiropractic manipulation, soft tissue therapies, and education about proper movement. Dr. DeFries selects care based on your examination findings, individual needs, and goals, with an emphasis on decreasing pain, improving function, and supporting ongoing mobility and wellness.</p><div className="mt-7"><CTAButton href="/book-online">Book Online →</CTAButton></div>
    <nav aria-label="Treatment sections" className="mt-10 flex flex-wrap gap-3">{TREATMENTS.map((t) => <Link key={t.id} href={`#${t.id}`} className="inline-flex min-h-11 items-center rounded-lg bg-cream px-4 py-3 text-sm font-semibold text-navy hover:bg-navy/10">{t.title}</Link>)}</nav>
    <section className="mt-12 rounded-2xl bg-cream p-7"><H2>What are we working toward?</H2><p className="mt-4 max-w-3xl text-ink">Your care starts with understanding what is affecting you and what you want to do more comfortably. The overall goals are to decrease pain and improve function.</p><ul className="mt-5 grid gap-3 sm:grid-cols-2"><li>Improve joint mobility</li><li>Reduce muscle spasm and tension</li><li>Restore strength, endurance, and coordination</li><li>Improve posture and movement habits</li><li>Address nerve irritation when appropriate for conservative care</li></ul><p className="mt-5 max-w-3xl text-ink">Within Dr. DeFries’s chiropractic approach, care also aims to support healthy nervous system function and overall well-being. Progress is assessed through your symptoms, examination findings, and everyday activities.</p></section>
    {TREATMENTS.map((t) => <section key={t.id} id={t.id} className="scroll-mt-28 border-b border-line py-10 sm:py-14"><div className={`grid gap-8 ${t.id === "soft-tissue" || t.id === "adjustment" ? "lg:grid-cols-[1.3fr_.7fr]" : "max-w-3xl"}`}><div><H2>{t.title}</H2>{t.paragraphs.map((p) => <p key={p} className="mt-4 text-base leading-relaxed text-ink">{p}</p>)}<div className="mt-6 flex items-center gap-4 text-navy"><GoalIcon kind={t.id === "exercise" ? "strength" : t.id === "posture" ? "reach" : "pain"}/><p className="text-sm font-semibold">{t.id === "exercise" ? "Strength, movement control, and everyday function" : t.id === "posture" ? "Movement habits, muscle control, and function" : t.id === "electrotherapy" ? "Goals vary with the type of stimulation used" : "Pain relief and more comfortable movement"}</p></div></div>{(t.id === "soft-tissue" || t.id === "adjustment") && <figure className="mx-auto w-full max-w-sm"><Image src={t.id === "adjustment" ? "/images/care/home-low-back-adjustment.jpg" : "/images/care/soft-tissue-care.jpg"} alt={t.id === "adjustment" ? "Dr. David DeFries performing a chiropractic adjustment during a home visit" : "Dr. David DeFries providing instrument-assisted soft tissue care during a home visit"} width={t.id === "adjustment" ? 360 : 1200} height={t.id === "adjustment" ? 480 : 1600} sizes="(min-width: 1024px) 384px, 100vw" className="h-auto w-full rounded-2xl"/></figure>}</div></section>)}
    <WholePersonBanner/><div className="mt-8"><CTAButton href="/book-online">Book Online →</CTAButton></div>
  </Container></article>;
}
